# Site settings
title: Nathan Long
email: nlong5@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I design and build websites for Fortune 500 companies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nathan-long.com" # the base hostname & protocol for your site
permalink: /blog/:title/
production: true
markdown: redcarpet
sass:
    style: :compressed
